### PR TITLE
Please credit the entire PMGH team, rather than one member.

### PR DESCRIPTION
**Pull request by LeoBadeaux**

### CODE REVIEW

**Review by afkvido — APPROVED** [review]

**Comment by jakepressley08** [comment]
ok im sorry i would like to be a mod still

**Comment by jakepressley08** [comment]
@LeoBadeaux @afkvido @0BunnySenpai0 @irhrhd can i still help

**Comment by afkvido** [comment]
Bro im not staff on this repo......... you can ping @0BunnySenpai0

**Comment by jakepressley08** [comment]
i emailed Caleb but he ain't respond

**Comment by jakepressley08** [comment]
@0BunnySenpai0

**Comment by jakepressley08** [comment]
he emailed me back i made it

**Pull request merged**
